M48
; DRILL file {KiCad 7.0.10} date sob, 20 kwi 2024, 00:48:09
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-20T00:48:09+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X170.11Y-106.395
X175.89Y-106.395
T2
X173.0Y-66.0
M30
